/**
 * 프롤로그 에러 코드
 *
 * 사용자에게 노출되는 모든 에러는 이 코드 중 하나를 사용한다.
 * 메시지는 카피 톤 가이드를 따른다.
 */

export const ErrorCode = {
  // 인증/계정
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  ACCOUNT_PENDING: 'ACCOUNT_PENDING',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
  ACCOUNT_WITHDRAWN: 'ACCOUNT_WITHDRAWN',
  IDENTITY_VERIFICATION_REQUIRED: 'IDENTITY_VERIFICATION_REQUIRED',
  FACE_VERIFICATION_REQUIRED: 'FACE_VERIFICATION_REQUIRED',
  PROFILE_INCOMPLETE: 'PROFILE_INCOMPLETE',

  // 가입
  PHONE_ALREADY_REGISTERED: 'PHONE_ALREADY_REGISTERED',
  AGE_NOT_ELIGIBLE: 'AGE_NOT_ELIGIBLE',
  REQUIRED_CONSENT_MISSING: 'REQUIRED_CONSENT_MISSING',
  OTP_INVALID: 'OTP_INVALID',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_TOO_MANY_ATTEMPTS: 'OTP_TOO_MANY_ATTEMPTS',

  // 카카오 로그인 (FR-A02)
  KAKAO_ALREADY_REGISTERED: 'KAKAO_ALREADY_REGISTERED',
  KAKAO_NOT_REGISTERED: 'KAKAO_NOT_REGISTERED',
  KAKAO_AUTH_FAILED: 'KAKAO_AUTH_FAILED',

  // 인증 외부 서비스
  IDENTITY_PROVIDER_ERROR: 'IDENTITY_PROVIDER_ERROR',
  FACE_VERIFICATION_FAILED: 'FACE_VERIFICATION_FAILED',
  FACE_NOT_DETECTED: 'FACE_NOT_DETECTED',

  // 추천/매칭
  NO_RECOMMENDATIONS_AVAILABLE: 'NO_RECOMMENDATIONS_AVAILABLE',
  RECOMMENDATION_NOT_FOUND: 'RECOMMENDATIONS_NOT_FOUND',
  ALREADY_INTERESTED: 'ALREADY_INTERESTED',
  ALREADY_SKIPPED: 'ALREADY_SKIPPED',
  TARGET_NOT_AVAILABLE: 'TARGET_NOT_AVAILABLE',
  DAILY_LIMIT_REACHED: 'DAILY_LIMIT_REACHED',

  // 대화
  CONVERSATION_NOT_FOUND: 'CONVERSATION_NOT_FOUND',
  CONVERSATION_EXPIRED: 'CONVERSATION_EXPIRED',
  CONVERSATION_BLOCKED: 'CONVERSATION_BLOCKED',
  CONVERSATION_EXTENSION_NOT_ALLOWED: 'CONVERSATION_EXTENSION_NOT_ALLOWED',

  // 신고/차단
  ALREADY_BLOCKED: 'ALREADY_BLOCKED',
  CANNOT_REPORT_SELF: 'CANNOT_REPORT_SELF',
  CANNOT_BLOCK_SELF: 'CANNOT_BLOCK_SELF',

  // 일반
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  RATE_LIMIT: 'RATE_LIMIT',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
